/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestDriveRouteImport } from './routes/test-drive'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as AdvanceBookingRouteImport } from './routes/advance-booking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as CarsIdRouteImport } from './routes/cars.$id'

const TestDriveRoute = TestDriveRouteImport.update({
  id: '/test-drive',
  path: '/test-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvanceBookingRoute = AdvanceBookingRouteImport.update({
  id: '/advance-booking',
  path: '/advance-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const CarsIdRoute = CarsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CarsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advance-booking': typeof AdvanceBookingRoute
  '/cars': typeof CarsRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-drive': typeof TestDriveRoute
  '/cars/$id': typeof CarsIdRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advance-booking': typeof AdvanceBookingRoute
  '/cars': typeof CarsRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-drive': typeof TestDriveRoute
  '/cars/$id': typeof CarsIdRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advance-booking': typeof AdvanceBookingRoute
  '/cars': typeof CarsRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test-drive': typeof TestDriveRoute
  '/cars/$id': typeof CarsIdRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advance-booking'
    | '/cars'
    | '/cart'
    | '/contact'
    | '/products'
    | '/sitemap.xml'
    | '/test-drive'
    | '/cars/$id'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/advance-booking'
    | '/cars'
    | '/cart'
    | '/contact'
    | '/products'
    | '/sitemap.xml'
    | '/test-drive'
    | '/cars/$id'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advance-booking'
    | '/cars'
    | '/cart'
    | '/contact'
    | '/products'
    | '/sitemap.xml'
    | '/test-drive'
    | '/cars/$id'
    | '/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdvanceBookingRoute: typeof AdvanceBookingRoute
  CarsRoute: typeof CarsRouteWithChildren
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestDriveRoute: typeof TestDriveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-drive': {
      id: '/test-drive'
      path: '/test-drive'
      fullPath: '/test-drive'
      preLoaderRoute: typeof TestDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advance-booking': {
      id: '/advance-booking'
      path: '/advance-booking'
      fullPath: '/advance-booking'
      preLoaderRoute: typeof AdvanceBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/cars/$id': {
      id: '/cars/$id'
      path: '/$id'
      fullPath: '/cars/$id'
      preLoaderRoute: typeof CarsIdRouteImport
      parentRoute: typeof CarsRoute
    }
  }
}

interface CarsRouteChildren {
  CarsIdRoute: typeof CarsIdRoute
}

const CarsRouteChildren: CarsRouteChildren = {
  CarsIdRoute: CarsIdRoute,
}

const CarsRouteWithChildren = CarsRoute._addFileChildren(CarsRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdvanceBookingRoute: AdvanceBookingRoute,
  CarsRoute: CarsRouteWithChildren,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestDriveRoute: TestDriveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
